project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!*.Rmd"

lang: kr
date-format: "YYYY년 MM월 DD일"

website:
  title: "chatGPT"
  favicon: "images/profile.png"
  google-analytics: "UA-229551680-1"
  search:
    location: navbar
    type: overlay
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "생성 AI"
        menu:
        - href: architecture.qmd
          text: "chatGPT 이해"
        - href: trends.qmd
          text: "추세 트렌드"
        - href: why_llm.qmd
          text: "왜 거대언어모형인가?"
        - href: gpt4_performance.qmd
          text: "GPT-4 성능"
        - text: "------------------"
        - href: interface.qmd
          text: "인터페이스"
        - href: interview.qmd
          text: "데이터 과학문제"
        - href: deepL.qmd
          text: "DeepL 번역 API"
      - text: "chatGPT 응용사례"
        menu:
        - href: use-cases.qmd
          text: "활용사례"
        - href: intro_avi.qmd
          text: "법인 R 소개영상"
        - href: macbook.qmd
          text: "맥북 투척사건"
        - href: office.qmd
          text: "오피스 전쟁"
        - href: about_gpt.qmd
          text: "GPT 역사"
        - text: "------------------"
        - href: news_article.qmd
          text: "보도자료 작성"
        - href: intro_book.qmd
          text: "데이터 과학 책"
        - href: intro_paper.qmd
          text: "논문 초록"
        - href: rnd.qmd
          text: "학술연구(R&D)"
        - href: yuji.qmd
          text: "멤버 Yuji"
        - text: "------------------"
        - href: text2image.qmd
          text: "텍스트 → 이미지 생성"
        - href: stable_diffusion.qmd
          text: "Stable Diffusion"
        - text: "------------------"
        - href: samsung.qmd
          text: "삼전 주가예측"
        - href: calculator.qmd
          text: "계산기 프로그램"
        - href: rcoding.qmd
          text: "GPT R 코딩개발"
        - href: rcoding-copilot.qmd
          text: "부조종사 R 코딩개발"
        - text: "------------------"
        - href: math.qmd
          text: "수학문제 (MIT)"
        - href: middle_school.qmd
          text: "Shiny 앱"
      - text: "BERT"
        menu:
        - href: ide.qmd
          text: "통합개발환경(IDE)"
        - text: "------------------"
        - href: reticulate.qmd
          text: "파이썬 환경구축"
        - href: koGPT.qmd
          text: "HuggingfaceR - 모형통계"
        - href: BERT.qmd
          text: "BERT"
        - text: "------------------"
        - href: hf.qmd
          text: "Hugging Face"
        - href: hf_windows.qmd
          text: "Hugging Face(윈도우)"
        - text: "------------------"
        - href: hf_pipeline.qmd
          text: "HF 파이프라인"
      - href: blog.qmd
        text: "게시글"
      - text: "유/무료 서비스"
        menu:
        - href: services.qmd
          text: "(유)무료 서비스"
    right:
      - icon: github
        href: https://github.com/bit2r/chatGPT
      - href: https://r2bit.com
        text: "R사용자회"
      - icon: github
        text: "Open Assistant"
        href: https://github.com/LAION-AI/Open-Assistant
      - text: "RTutor"
        href: https://rtutor.ai/
      - text: "About"
        href: about.qmd
  page-footer:
    center: |
      [한국 R 사용자회](mailto:admin@r2bit.com)
    left: |
      [Quarto](https://quarto.org/) 개발
    right: |
      [Github 코드 저장소](https://github.com/bit2r/chatGPT)
    background: "#2780e3"

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: css/quarto.css
    code-link: true
    code-fold: show
    code-tools: true
    code-block-bg: "white"
    code-block-border-left: "#31BAE9"
    highlight-style: github
    toc: true

execute:
  freeze: true
