project:
  type: website
  output-dir: docs
  resources:
    - "data/*.mp3"
    - "data/LibriSpeech/*.mp3"
    - "data/제84주년_31절_기념사_노무현.mp3"
  render:
    - "*.qmd"
    - "!*.Rmd"

lang: ko
date-format: "YYYY년 MM월 DD일"

website:
  title: "chatGPT"
  favicon: "images/profile.png"
  google-analytics: "UA-229551680-1"
  search:
    location: navbar
    type: overlay
  navbar:
    left:
      - text: "챗GPT4"
        menu:
        - href: devday.qmd
          text: "OpenAI 개발자 날"

      - text: "생성 AI"
        menu:
        - href: architecture.qmd
          text: "chatGPT 이해"
        - href: trends.qmd
          text: "추세 트렌드"
        - href: why_llm.qmd
          text: "왜 거대언어모형인가?"
        - href: nlp_LLM.qmd
          text: "NLP와 LLM"
        - href: gpt4_performance.qmd
          text: "GPT-4 성능"
        - href: gpt-security.qmd
          text: "챗GPT 보안사고"
        - text: "------------------"
        - href: interface.qmd
          text: "인터페이스"
        - href: open_source.qmd
          text: "오픈소스 S/W LLM"

      - text: "chatGPT 응용사례"
        menu:
        - href: use-cases.qmd
          text: "활용사례"
        - href: intro_avi.qmd
          text: "법인 R 소개영상"
        - href: macbook.qmd
          text: "맥북 투척사건"
        - href: office.qmd
          text: "오피스 전쟁"
        - text: "------------------"
        - href: news_article.qmd
          text: "보도자료 작성"
        - href: intro_book.qmd
          text: "데이터 과학 책"
        - href: intro_paper.qmd
          text: "논문 초록"
        - href: rnd.qmd
          text: "학술연구(R&D)"
        - href: yuji.qmd
          text: "멤버 Yuji"
        - text: "------------------"
        - href: stable_diffusion.qmd
          text: "Stable Diffusion"
        - href: text_to_images.qmd
          text: "Text-to-Images"
        - href: text2image.qmd
          text: "`bitGPT` Text-to-Image"
        - text: "------------------"
        - href: samsung.qmd
          text: "삼전 주가예측"
        - href: calculator.qmd
          text: "계산기 프로그램"
        - href: rcoding.qmd
          text: "GPT R 코딩개발"
        - href: rcoding-copilot.qmd
          text: "부조종사 R 코딩개발"
        - text: "------------------"
        - href: math.qmd
          text: "수학: MIT / 수능"
        - href: middle_school.qmd
          text: "Shiny 앱"
        - href: inaugural.qmd
          text: "대통령 취임사"
        - href: translation.qmd
          text: "번역(영한, 한영)"
        - href: gg_grouping.qmd
          text: "챗GPT 팀구성"
        - text: "------------------"
        - href: biz_number_API.qmd
          text: "사업자등록증 API (국세청)"
        - href: plugin.qmd
          text: "챗GPT 플러그인"

      - text: "Prompt Eng."
        menu:
        - href: prompt.qmd
          text: "Prompt Engineering"
        - href: prompt_adv.qmd
          text: "Advanced Prompt Engineering"
        - href: prompt_in_practice.qmd
          text: "프롬프트 실무"
        - href: prompt_for_develoopers.qmd
          text: "(개발자) 프롬프트 공학"
        - text: "------------------"
        - href: prompt_data_science.qmd
          text: "데이터 과학 프롬프트"
        - href: interview.qmd
          text: "데이터 과학 인터뷰"

      - text: "자동화/개발"
        menu:
        - href: ide.qmd
          text: "통합개발환경(IDE)"
        - href: reticulate.qmd
          text: "파이썬 환경구축"
        - text: "------------------"
        - href: openAI_api.qmd
          text: "OpenAI API 프로그래밍"
        - href: openAI_api_apps.qmd
          text: "OpenAI API 응용프로그램"
        - href: langchain_arch.qmd
          text: "LangCahin 아키텍쳐"
        - href: whisper.qmd
          text: "오정보 음성인식(Whisper)"
        - href: news_release.qmd
          text: "오정보 요약"
        - href: misinfo_embedding.qmd
          text: "오정보 임베딩"
        - text: "------------------"
        - href: shiny_chatGPT.qmd
          text: "Shiny 챗GPT"
        - text: "------------------"
        - href: palmer_penguins.qmd
          text: "펭귄 데이터셋"
        - href: penguins_analytics.qmd
          text: "챗GPT 펭귄 데이터 분석"
        - href: three_paradigm.qmd
          text: "Code Interpreter, Notable"
        - href: penguin_analysis.qmd
          text: "심슨 패러독스"
        - text: "데이터 과학 AutoGPT"
        - text: "------------------"
        - href: pandasai.qmd
          text: "판다스 AI"
        - href: llama_penguins.qmd
          text: "펭귄: 라마인덱스"
        - href: sql_openai.qmd
          text: "챗GPT SQL"
        - text: "------------------"
        - href: hf.qmd
          text: "Hugging Face"
        - href: hf_windows.qmd
          text: "Hugging Face(윈도우)"
        - href: hf_pipeline.qmd
          text: "HF 파이프라인"
        - href: koGPT.qmd
          text: "HuggingfaceR - 모형통계"
        - href: BERT.qmd
          text: "BERT"

      - href: blog.qmd
        text: "게시글"
      - text: "비즈니스"
        menu:
        - href: chatGPT_overview.qmd
          text: "챗GPT 개요"
    right:
      - icon: github
        href: https://github.com/bit2r/chatGPT
      - href: https://r2bit.com
        text: "R사용자회"
      - icon: github
        text: "Open Assistant"
        href: https://github.com/LAION-AI/Open-Assistant
      - text: "RTutor"
        href: https://rtutor.ai/
      - text: "About"
        href: about.qmd
  page-footer:
    center: |
      [한국 R 사용자회](mailto:admin@r2bit.com)
    left: |
      [Quarto](https://quarto.org/) 개발
    right: |
      [Github 코드 저장소](https://github.com/bit2r/chatGPT)
    background: "#2780e3"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: css/quarto.css
    code-link: true
    code-fold: show
    code-tools: true
    code-block-bg: "white"
    code-block-border-left: "#31BAE9"
    highlight-style: github
    toc: true


bibliography: bibliography.bib
csl: apa-single-spaced.csl
link-citations: true

execute:
  freeze: auto
