project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!*.Rmd"

lang: kr
date-format: "YYYY년 MM월 DD일"

website:
  title: "chatGPT"
  favicon: "images/profile.png"
  search:
    location: navbar
    type: overlay
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "BERT"
        menu:
        - href: reticulate.qmd
          text: "파이썬 환경구축"
        - href: koGPT.qmd
          text: "HuggingfaceR - 모형통계"
        - href: BERT.qmd
          text: "BERT"
        - text: "------------------"
        - href: hf.qmd
          text: "Hugging Face"
        - href: hf_windows.qmd
          text: "Hugging Face(윈도우)"
        - text: "------------------"
        - href: hf_pipeline.qmd
          text: "HF 파이프라인"
      - text: "Generative AI"
        menu:
        - href: project.qmd
          text: "Projects"
        - href: codex.qmd
          text: "OpenAI Codex"
        - href: image2image.qmd
          text: "이미지 생성"
        - href: math.qmd
          text: "수학문제"
        - href: rcoding.qmd
          text: "R 코딩개발"
        - href: interview.qmd
          text: "데이터 과학문제"
      - text: "SEN"
        menu:
        - href: deepL.qmd
          text: "DeepL 번역 API"
        - href: middle_school.qmd
          text: "중학수학 - 연립방정식"
      - href: blog.qmd
        text: "게시글"
    right:
      - icon: github
        href: https://github.com/bit2r/chatGPT
      - href: https://r2bit.com
        text: "R사용자회"
      - icon: github
        text: "Open Assistant"
        href: https://github.com/LAION-AI/Open-Assistant
      - text: "RTutor"
        href: https://rtutor.ai/
      - text: "About"
        href: about.qmd
  page-footer:
    center: |
      [한국 R 사용자회](mailto:admin@r2bit.com)
    left: |
      [Quarto](https://quarto.org/) 개발
    right: |
      [Github 코드 저장소](https://github.com/bit2r/chatGPT)
    background: "#2780e3"

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: css/quarto.css
    code-link: true
    code-fold: show
    code-tools: true
    code-block-bg: "white"
    code-block-border-left: "#31BAE9"
    highlight-style: github
    toc: true

execute:
  freeze: true
