---
title: "chatGPT"
subtitle: "데이터 과학 인터뷰 문제"
author:
  - name: 이광춘
    url: https://www.linkedin.com/in/kwangchunlee/
    affiliation: 한국 R 사용자회
    affiliation-url: https://github.com/bit2r
title-block-banner: true
#title-block-banner: "#562457"
format:
  html:
    css: css/quarto.css
    theme: flatly
    code-fold: true
    toc: true
    toc-depth: 3
    toc-title: 목차
    number-sections: true
    highlight-style: github    
    self-contained: false
filters:
   - lightbox
   - interview-callout.lua
lightbox: auto
link-citations: true
knitr:
  opts_chunk: 
    message: false
    warning: false
    collapse: true
    comment: "#>" 
    R.options:
      knitr.graphics.auto_pdf: true
editor_options: 
  chunk_output_type: console
---

# 들어가는 질문

## 문제 1

::: {.custom-callout-tip collapse="true"}

기계학습 분류모형개발할 때 클래스 불균형(class imbalance) 문제를 어떻게 처리하나요?

:::


## 문제 2

::: {.custom-callout-tip collapse="true"}

기계학습모형에서 bias 와 variance trade-off에서 존재합니다. 
어떤 기계학습 모형이 bias 와 variance를 줄이는데 효과적으로 알려져 있나요?
:::

## 문제 3

::: {.custom-callout-tip collapse="true"}

리스트와 데이터프레임 자료구조의 차이점에 대해서 말씀해 주세요.
:::

## 문제 4

::: {.custom-callout-tip collapse="true"}

feature engineering, data preprocessing, data cleansing이 어떻게 다른지 설명하세요.
:::

## 문제 5

::: {.custom-callout-tip collapse="true"}

제품 설명 등 텍스트 필드 칼럼이 있습니다. 기계학습 알고리즘 분류나 예측 모형에 적용시킬 수 있는 방법을 설명해주세요.
:::


# DS topic

## Visualization

::: {.custom-callout-tip collapse="true"}

Data Analytics에서 시각화는 매우 중요합니다. 
어떻게 가르칠것인지 커러큘럼, 교수방법, 프로젝트 진행방법, 평가방법에 대해서 말씀해주세요. (5분)

:::

## EDA

::: {.custom-callout-tip collapse="true"}

탐색적 데이터 분석(EDA)가 훌륭한 기계학습 알고리즘 개발과 함께 매우 중요합니다. 어떻게 가르칠것인지 커러큘럼, 교수방법, 프로젝트 진행방법, 평가방법에 대해서 말씀해주세요. (5분)

:::

# Problem Statement 

::: {.custom-callout-tip collapse="true"}

역사가 오래된 대기업일수록 20대부터 50대까지 다양한 연령층의 직원분들이 근무를 하고 계십니다. 서로 다른 학습목적을 갖고, 다양한 연령대, 컴퓨팅 이해도와 스킬이 다르고 학습에 투여할 수 있는 시간이 다른 분들로 구성된 15명 내외 수강상을 대상으로 데이터 과학 기초과정을 강의해야 하는데 이는 동일한 연령대 동일한 기술, 동일한 관심사, 동일한 학습비용을 지불하고 동일한 시간을 투여할 수 있는 상황이 아닙니다. 이러한 여건하에서 어떻게 하면 학습목표를 달성할 수 있을까요?

:::


