---
title: "chatGPT"
subtitle: "수능 수학(Mathpix)"
description: | 
  수능 수학문제를 OCR (Mathpix)와 챗GPT를 사용해서 풀어보자.
author:
  - name: 이광춘
    url: https://www.linkedin.com/in/kwangchunlee/
    affiliation: 한국 R 사용자회
    affiliation-url: https://github.com/bit2r
title-block-banner: true
#title-block-banner: "#562457"
format:
  html:
    css: css/quarto.css
    theme: flatly
    code-fold: true
    code-tools: true
    code-link: true
    code-overflow: wrap
    toc: true
    toc-depth: 3
    toc-title: 목차
    number-sections: true
    highlight-style: github    
    self-contained: false
filters:
   - lightbox

lightbox: auto
link-citations: true
knitr:
  opts_chunk: 
    message: false
    warning: false
    collapse: true
    comment: "#>" 
    R.options:
      knitr.graphics.auto_pdf: true
editor_options: 
  chunk_output_type: console
notebook-view:
  - notebook: jupyterlab/pinecone.ipynb
    title: "벡터 DB 쥬피터 노트북"
---


```{r}
#| include: false
library(mathpix)
library(tidyverse)
```


# `LaTeX` 설치

`tinytex::install_tinytex()` 명령어로 `$\LaTeX$`을 설치한다.

```{r}
#| eval: false
tinytex::install_tinytex()
# 설치위치 확인
tinytex::tinytex_root()
```

## 헬로월드


```{r}
writeLines(c(
  '\\documentclass{article}',
  '\\begin{document}', 'Hello world!', '\\end{document}'
), 'pdf/test_eng.tex')

tinytex::pdflatex('pdf/test_eng.tex')
```


# `mathpix` 패키지

```{r}
#| eval: false
library(mathpix)
mathpix("images//integral.jpg")
```

$$
 \int \frac { 4 x } { \sqrt { x ^ { 2 } + 1 } } d x 
$$

# `pdf` &rarr; `.png`

2023년 수능 PDF 수학문제 파일을 이미지(`.png`) 파일로 변환시키자.

```{r}
#| eval: false
library(pdftools)

pdf_convert("data/2교시_수학영역_문제지.pdf", format = "png", pages=1, filenames = "pdf/math_01.png")
```


```{r}
math_01_png <- mathpix("pdf/math_01.png", insert = FALSE)
```

$$
 g ( x ) = x ^ { 2 } f ( x ) 
$$
```{r}
math_01_png
```

